name: Deploy to MongoDB Atlas

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Generate terraform.tfvars.json
        run: |
          echo '{
            "public_key": "${{ secrets.PUBLIC_KEY }}",
            "private_key": "${{ secrets.PRIVATE_KEY }}",
            "project_id": "${{ secrets.PROJECT_ID }}",
            "project_name": "${{ secrets.PROJECT_NAME }}",
            "cluster_name": "${{ secrets.CLUSTER_NAME }}",
            "region": "${{ secrets.REGION }}",
            "mongodbversion": "${{ secrets.MONGODBVERSION }}"
          }' > terraform.tfvars.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars.json -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -var-file=terraform.tfvars.json -auto-approve